### ISSUE TITLE
could you use vue-demi to support Vue 2.x?

### ISSUE THREAD

**Issue by jueinin** [DamianOsipiuk/vue-react-query#1]
first of all. Thanks for this project.Ahh

I am very willing to provide this PR.

thanks. because my current working project still use vue 2.x.

**Comment by DamianOsipiuk** [comment]
Hi @jueinin 
I was thinking about the Vue 2 support, but unfortunately it is not as easy as switching the imports.
If this library would only provide some hooks, it might be working via vue-demi, but dev tools is a different story.

I would either have to rewrite them to be compatible with vue 2 and make a separate build, or rewrite them to use render function.

Another option would be to just make another rollup entry point and build only hooks for Vue 2.
If you can live without dev tools, then this should be the easiest option.

**Comment by jueinin** [comment]
OK I will try add another entry point for rollup.  By the way, why need to rewrite dev tools by render function to support Vue 2.x ?

it seems that we can directly replace `import xx from 'vue'`  to  `import xx from 'vue-demi'`

**Comment by DamianOsipiuk** [comment]
Templates in Vue are compiled and use additional imports from Vue which cannot be changed. You can check that in the compiled bundle.
Additionally templates in Vue 3 use some features that are not available in Vue 2. Ex. Fragments cannot be used with Vue 2.
Therefore SFCs cannot be made compatible with Vue 3 and 2 at the same time without additional work.
