### ISSUE TITLE
Error with Vue 2 - No queryClient found in Vue context

### ISSUE THREAD

**Issue by onkarj422** [DamianOsipiuk/vue-react-query#4]
Hello,

Tried this out with my Vue 2 codebase.

This is how I am mounting app
```
import { QueryClient, VUE_QUERY_CLIENT } from "vue-react-query";

import VueCompositionApi from "@vue/composition-api";
import { createApp, h } from "@vue/composition-api";

Vue.use(VueCompositionApi);
const queryClient = new QueryClient();
queryClient.mount();
createApp({
  provide: {
    [VUE_QUERY_CLIENT]: queryClient
  },
  router,
  store,
  render: () => h(App)
}).mount("#app");

```

And this is how I am using it in my component
```
export default {
  setup() {
    const { isLoading, isError, isFetching, data, error, refetch } = useQuery(
      "todos",
      todoFetcher,
      {
        retry: 0,
        staleTime: 1000,
        cacheTime: 2000
      }
    );
    return { isLoading, isError, isFetching, data, error, refetch };
  },
  name: "home"
};
```

Here are my dependencies
```
"dependencies": {
    "@vue/composition-api": "^1.0.0-rc.7",
    "core-js": "^3.4.4",
    "vue": "^2.6.11",
    "vue-class-component": "^7.0.2",
    "vue-property-decorator": "^8.3.0",
    "vue-react-query": "^0.4.0",
  },
```

And this is the error I am getting
![image](https://user-images.githubusercontent.com/20082972/115603990-77c93500-a2fe-11eb-870d-da826ec9823d.png)

Also, getting this warning in a different codebase. 
![image](https://user-images.githubusercontent.com/20082972/115608258-ab5a8e00-a303-11eb-8326-49b01f81974b.png)

Thank you!

**Comment by DamianOsipiuk** [comment]
Hi, unfortunately `mount` function on QueryClient does not return the instance. Therefore you cannot chain it like you have done 😞 
https://github.com/tannerlinsley/react-query/blob/5f7363518a8e0549bc7f9707cb257f09384c7b09/src/core/queryClient.ts#L75

As of now you need to create intermediate variable for QueryClient.
Ex. https://github.com/DamianOsipiuk/vue-react-query/blob/main/examples/basic-vue-2.x/src/main.ts

I will create a ticket in the main package to fix that in the future.

**Comment by onkarj422** [comment]
> Hi, unfortunately `mount` function on QueryClient does not return the instance. Therefore you cannot chain it like you have done 😞
> https://github.com/tannerlinsley/react-query/blob/5f7363518a8e0549bc7f9707cb257f09384c7b09/src/core/queryClient.ts#L75
> 
> As of now you need to create intermediate variable for QueryClient.
> Ex. https://github.com/DamianOsipiuk/vue-react-query/blob/main/examples/basic-vue-2.x/src/main.ts
> 
> I will create a ticket in the main package to fix that in the future.

Actually, I tried it with the intermediate variables also. In fact tried that first. Getting the same error.

**Comment by onkarj422** [comment]
Okay, my bad. It is working with intermediate variable. Thanks!

But then, when I tried to change my setup function a little bit. Let's suppose this -
```
export default function setup(props, context) {
    const useModelObjectQuery = (objectId, changesetId) => {
        return useQuery(
            'modelObjects',
            () => new Promise((resolve, reject) => {
                inputDataHttpClient.getObjectsByClassId(objectId, changesetId).subscribe((r) => resolve(r), (e) => reject(e));
            }),
        )
    } 
    return {
        useModelObjectQuery,
    }
}
```

and then call useModelObjectQuery in the component like
```
const modelObjectQuery = this.useModelObjectQuery();
```

Throws the same error - "No queryClient found in Vue context".

Any idea? @DamianOsipiuk

**Comment by DamianOsipiuk** [comment]
Hmm i do not have the full context of the example that you are providing, but it seems that you are wrapping `useQuery` with another outer function, that is not invoked immidiately.

Unfortunately `provide/inject` pattern works only inside setup function. Therefore `useQuery` has to be called inside setup function to work properly.

If you want for example to not fetch immidiately, then there are some options like setting `enabled` to false and then invoking refetch manually etc. Please refer to the react-query documentation for more details.

**Comment by onkarj422** [comment]
> Hmm i do not have the full context of the example that you are providing, but it seems that you are wrapping `useQuery` with another outer function, that is not invoked immidiately.
> 
> Unfortunately `provide/inject` pattern works only inside setup function. Therefore `useQuery` has to be called inside setup function to work properly.
> 
> If you want for example to not fetch immidiately, then there are some options like setting `enabled` to false and then invoking refetch manually etc. Please refer to the react-query documentation for more details.

Thanks! 
I actually wrap my useQuery with outer function because I need to pass some parameters which are available in the component to the query function.

**Comment by DamianOsipiuk** [comment]
Then it depends from where do you get those parameters.

If those are set via `data`, `computed`, `watch`, then those can be converted to the compositionAPI and composed with `useQuery` in the same closure.

If those are fetched from somewhere or converting is not an option then you have few options. Basically they would boil down to exposing a ref from setup function and use it in the queryKey. Then whenever you will update the value of a `ref` it should refetch the data with updated parameters.

**Comment by onkarj422** [comment]
Thanks! Tried your last suggestion.
Now, the setup function looks like this
```
const fetchModelObjects = ({ queryKey }) => new Promise((resolve, reject) => {
    const [_key, { studyId, changesetId, classId }] = queryKey;
    inputDataHttpClient.getObjectsByClassId(studyId, changesetId, classId)
        .subscribe((res) => resolve(res), (err) => reject(err));
});

export default function setup(props, context) {
    const params = reactive({
        studyId: '',
        changesetId: '',
        classId: null,
    });
    const createContext = (_studyId, _changesetId, _classId) => {
        params.studyId = _studyId;
        params.changesetId = _changesetId;
        params.classId = _classId;
    };
    const modelObjectsQuery: any = useQuery(
        ['modelObjects', params],
        fetchModelObjects,
        {
            enabled: Object.values(params).every(Boolean),
        }
    );
    watch(params, (newValue) => {
        if (newValue) {
            const refetch = unref(modelObjectsQuery.refetch);
            refetch();
        }
    });
    return {
        createContext,
        modelObjectsQuery,
    };
}
```

and then in component, I am calling this
```
this.createContext(this.studyId, this.changesetId, this.classId);
```
This works. Essentially, this.createContext now looks like a function which initiates the API call.
So, the fact that I am not able to wrap useQuery inside another function still feels sad. And if you look at the setup function, that's a lot of code I had to write in order to be able to pass parameters from my component.
So, is passing parameters from component anti pattern in terms of composition api?

**Comment by DamianOsipiuk** [comment]
It's hard to tell if it's an anti-pattern since Vue3 / composition API is pretty fresh.
However, composition API can handle all of the things that were previously available as component parts (data, computed, lifecycle, etc.). Therefore I would say, that if you can, you should rewrite it with composition API, which should reduce the need for boilerplate.

Also, you could create your own hook that will contain the useQuery inside and will hide all of this additional logic, exposing only parts that are needed outside. You just need to make sure that you are calling the useQuery inside the setup function for the provide/inject to work.

Glad it's working :1st_place_medal:

**Comment by onkarj422** [comment]
> It's hard to tell if it's an anti-pattern since Vue3 / composition API is pretty fresh.
> However, composition API can handle all of the things that were previously available as component parts (data, computed, lifecycle, etc.). Therefore I would say, that if you can, you should rewrite it with composition API, which should reduce the need for boilerplate.
> 
> Also, you could create your own hook that will contain the useQuery inside and will hide all of this additional logic, exposing only parts that are needed outside. You just need to make sure that you are calling the useQuery inside the setup function for the provide/inject to work.
> 
> Glad it's working 🥇

I think I got the wrapping useQuery in other function working. And I think it was something to do with arrow functions. It works when I use plain JS function.

Thanks a lot for all the suggestions. I think I will need a lot of refactoring as well as a lot of composing in order to be able to use vue-react-query flawlessly in my codebase.
I am actually going to try and refactor and remove some of my Vuex modules and replace the whole thing with vue-react-query.

So, let's see how it goes! It's a big task, but I will keep reporting if I find anything odd.
Wish me luck!!

Thanks again!

Closing this as the main issue is resolved!

**Comment by DamianOsipiuk** [comment]
@onkarj422 Yeah, all feedback is appreciated as I cannot test all the scenarios by myself, unfortunately :wink:
Therefore if you find something odd, or maybe some improvements that could make the usage easier, I'm all ears :ear:
